from __future__ import annotations

import io
import zipfile
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse, JSONResponse
from sqlmodel import select

from database import get_session
from dependencies import get_current_user, get_owned_project
from models.db import Project, Task, User
from models.enums import SDLCPhase, TaskStatus
from services.file_parser import merge_outputs, detect_project_type, default_start_command

router = APIRouter()

_PHASE_LABEL: dict[SDLCPhase, str] = {
    SDLCPhase.DISCOVERY:      "Requirements",
    SDLCPhase.ARCHITECTURE:   "Architecture",
    SDLCPhase.IMPLEMENTATION: "Implementation",
    SDLCPhase.TESTING:        "Testing",
    SDLCPhase.SRE_REVIEW:     "SRE Review",
}

_DOC_PHASES: dict[str, list[SDLCPhase]] = {
    "requirements": [SDLCPhase.DISCOVERY],
    "architecture": [SDLCPhase.ARCHITECTURE],
    "design":       [SDLCPhase.DISCOVERY, SDLCPhase.ARCHITECTURE],
}


def _slug(name: str) -> str:
    return name.lower().replace(" ", "-").replace("/", "-")


def _phase_markdown(label: str, tasks: list[Task]) -> str:
    done = [t for t in tasks if t.status == TaskStatus.DONE and t.output]
    if not done:
        return f"# {label}\n\n_No completed tasks yet._\n"
    parts = [f"# {label}\n"]
    for t in done:
        parts.append(f"## {t.title}\n\n{t.output}\n")
    return "\n".join(parts)


def _readme(project: Project, tasks: list[Task], project_type: str, start_cmd: str) -> str:
    done = sum(1 for t in tasks if t.status == TaskStatus.DONE)
    lines = [
        f"# {project.name}",
        "",
        f"> {project.description}",
        "",
        f"**Status:** {project.status.value}  ",
        f"**Phase:** {project.current_phase.value}  ",
        f"**Tasks completed:** {done}/{len(tasks)}  ",
        f"**Project type:** {project_type}",
        "",
        "## Quick Start",
        "",
        "```bash",
        start_cmd,
        "```",
        "",
        "## Documentation",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| `docs/requirements.md` | Discovery — requirements & tech stack |",
        "| `docs/architecture.md` | Architecture — system design, API contracts, data models |",
        "| `docs/testing.md` | Testing — test plan and test cases |",
        "| `docs/sre-review.md` | SRE Review — infrastructure & reliability |",
        "",
        "---",
        "_Generated by SDLC Orchestrator_",
    ]
    return "\n".join(lines) + "\n"


async def _load(project_id: str, current_user: User, session: Any) -> tuple[Project, list[Task]]:
    proj = await get_owned_project(project_id, current_user, session)
    tasks = list(
        (await session.exec(
            select(Task).where(Task.project_id == project_id).order_by(Task.created_at.asc())
        )).all()
    )
    return proj, tasks


@router.get("/{project_id}/download")
async def download_project_zip(
    project_id: str,
    session: Any = Depends(get_session),
    current_user: User = Depends(get_current_user),
) -> StreamingResponse:
    project, tasks = await _load(project_id, current_user, session)

    all_outputs = [t.output for t in tasks if t.status == TaskStatus.DONE and t.output]
    merged = merge_outputs(all_outputs)

    project_type = detect_project_type(merged.files)
    start_cmd = merged.start_command or default_start_command(project_type)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # README at root
        zf.writestr("README.md", _readme(project, tasks, project_type, start_cmd))

        # Actual source files from agent outputs
        for path, content in merged.files.items():
            zf.writestr(path, content)

        # Docs folder — one MD per phase
        for phase, label in _PHASE_LABEL.items():
            if phase == SDLCPhase.IMPLEMENTATION:
                continue  # source files already included above
            phase_tasks = [t for t in tasks if t.phase == phase]
            zf.writestr(f"docs/{_slug(label)}.md", _phase_markdown(label, phase_tasks))

    buf.seek(0)
    safe = _slug(project.name)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{safe}.zip"'},
    )


@router.get("/{project_id}/docs/{doc_type}")
async def download_doc(
    project_id: str,
    doc_type: str,
    session: Any = Depends(get_session),
    current_user: User = Depends(get_current_user),
) -> StreamingResponse:
    if doc_type not in _DOC_PHASES:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown doc type '{doc_type}'. Use: requirements, architecture, design",
        )
    project, tasks = await _load(project_id, current_user, session)
    phases = _DOC_PHASES[doc_type]
    sections = [f"# {project.name} — {doc_type.capitalize()}\n"]
    for phase in phases:
        phase_tasks = [t for t in tasks if t.phase == phase]
        sections.append(_phase_markdown(_PHASE_LABEL[phase], phase_tasks))
    content = "\n".join(sections)
    filename = f"{_slug(project.name)}-{doc_type}.md"
    return StreamingResponse(
        iter([content.encode()]),
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{project_id}/preview-info")
async def preview_info(
    project_id: str,
    session: Any = Depends(get_session),
    current_user: User = Depends(get_current_user),
) -> JSONResponse:
    project, tasks = await _load(project_id, current_user, session)

    all_outputs = [t.output for t in tasks if t.status == TaskStatus.DONE and t.output]
    merged = merge_outputs(all_outputs)

    project_type = detect_project_type(merged.files)
    start_cmd = merged.start_command or default_start_command(project_type)
    is_web = project_type in ("nextjs", "react", "node")

    return JSONResponse({
        "project_type": project_type,
        "is_web": is_web,
        "start_command": start_cmd,
        "files": merged.files,
        "file_count": len(merged.files),
    })
