"""GitHub integration service: PAT encryption, code push, and PR creation."""

from __future__ import annotations

import base64
import logging
import os
from typing import Any, Optional

import httpx
from cryptography.fernet import Fernet

from sqlmodel import select

logger = logging.getLogger(__name__)

GITHUB_API_BASE = "https://api.github.com"
_GH_HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def _fernet() -> Fernet:
    key = os.getenv("GITHUB_TOKEN_KEY", "")
    if not key:
        raise RuntimeError("GITHUB_TOKEN_KEY environment variable not set")
    return Fernet(key.encode())


def encrypt_pat(pat: str) -> str:
    return _fernet().encrypt(pat.encode()).decode()


def decrypt_pat(enc: str) -> str:
    return _fernet().decrypt(enc.encode()).decode()


def _auth_headers(pat: str) -> dict:
    return {**_GH_HEADERS, "Authorization": f"Bearer {pat}"}


async def validate_pat(pat: str) -> bool:
    """Return True if the PAT authenticates successfully against GitHub."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GITHUB_API_BASE}/user",
            headers=_auth_headers(pat),
            timeout=10.0,
        )
    return resp.status_code == 200


async def validate_repo(pat: str, owner_repo: str) -> bool:
    """Return True if the repo exists and is accessible with the PAT."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner_repo}",
            headers=_auth_headers(pat),
            timeout=10.0,
        )
    return resp.status_code == 200


async def _get_default_branch(pat: str, owner_repo: str) -> str:
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner_repo}",
            headers=_auth_headers(pat),
            timeout=10.0,
        )
    resp.raise_for_status()
    return resp.json()["default_branch"]


async def _get_branch_sha(pat: str, owner_repo: str, branch: str) -> Optional[str]:
    """Return HEAD commit SHA of a branch, or None if it doesn't exist."""
    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/git/ref/heads/{branch}",
            headers=_auth_headers(pat),
            timeout=10.0,
        )
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    return resp.json()["object"]["sha"]


async def _ensure_branch(pat: str, owner_repo: str, branch: str, base_branch: str) -> None:
    """Create branch from base_branch if it doesn't already exist."""
    if await _get_branch_sha(pat, owner_repo, branch) is not None:
        return
    base_sha = await _get_branch_sha(pat, owner_repo, base_branch)
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/git/refs",
            headers=_auth_headers(pat),
            json={"ref": f"refs/heads/{branch}", "sha": base_sha},
            timeout=10.0,
        )
    resp.raise_for_status()


async def _push_file(
    pat: str,
    owner_repo: str,
    branch: str,
    path: str,
    content: str,
    message: str,
) -> None:
    """Create or update a file on a branch via the GitHub contents API."""
    encoded = base64.b64encode(content.encode()).decode()

    async with httpx.AsyncClient() as client:
        # Fetch existing file SHA (needed for updates)
        existing = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/contents/{path}",
            headers=_auth_headers(pat),
            params={"ref": branch},
            timeout=10.0,
        )
        payload: dict = {"message": message, "content": encoded, "branch": branch}
        if existing.status_code == 200:
            payload["sha"] = existing.json()["sha"]

        resp = await client.put(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/contents/{path}",
            headers=_auth_headers(pat),
            json=payload,
            timeout=30.0,
        )
    resp.raise_for_status()


async def push_implementation(
    pat: str,
    owner_repo: str,
    branch: str,
    project_name: str,
    messages: list,
) -> None:
    """Push all implementation agent messages as a markdown file to the branch."""
    default_branch = await _get_default_branch(pat, owner_repo)
    await _ensure_branch(pat, owner_repo, branch, default_branch)

    parts = [f"# {project_name} — Implementation\n\nGenerated by SDLC Orchestrator.\n\n---\n\n"]
    for msg in messages:
        parts.append(f"## Agent Output\n\n{msg.content}\n\n---\n\n")

    await _push_file(
        pat, owner_repo, branch,
        path="sdlc/implementation.md",
        content="".join(parts),
        message=f"feat: SDLC implementation output for {project_name}",
    )


async def create_pr(
    pat: str,
    owner_repo: str,
    branch: str,
    title: str,
    body: str,
) -> str:
    """Open a PR from branch → default branch. Returns the PR URL.

    If an open PR already exists for that branch, returns its URL without creating a duplicate.
    """
    default_branch = await _get_default_branch(pat, owner_repo)
    owner = owner_repo.split("/")[0]

    async with httpx.AsyncClient() as client:
        existing = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/pulls",
            headers=_auth_headers(pat),
            params={"head": f"{owner}:{branch}", "state": "open"},
            timeout=10.0,
        )
        existing.raise_for_status()
        open_prs = existing.json()
        if open_prs:
            return open_prs[0]["html_url"]

        resp = await client.post(
            f"{GITHUB_API_BASE}/repos/{owner_repo}/pulls",
            headers=_auth_headers(pat),
            json={"title": title, "body": body, "head": branch, "base": default_branch},
            timeout=10.0,
        )
    resp.raise_for_status()
    return resp.json()["html_url"]


async def auto_push(project: Any, session: Any) -> str:
    """Push implementation content on IMPLEMENTATION→TESTING transition.

    Returns 'success' | 'skipped' | 'failed'.
    """
    from models.db import User, AgentMessage

    if not project.github_repo or not project.user_id:
        return "skipped"

    user_result = await session.exec(select(User).where(User.id == project.user_id))
    user = user_result.first()
    if not user or not user.github_token_enc:
        return "skipped"

    try:
        pat = decrypt_pat(user.github_token_enc)
    except Exception:
        logger.warning("auto_push: could not decrypt PAT for project %s", project.id)
        return "skipped"

    branch = project.github_branch or f"sdlc/{project.id}"

    msg_result = await session.exec(
        select(AgentMessage).where(AgentMessage.project_id == project.id)
    )
    messages = msg_result.all()

    try:
        await push_implementation(pat, project.github_repo, branch, project.name, messages)
        return "success"
    except Exception as exc:
        logger.error("auto_push failed for project %s: %s", project.id, exc)
        return "failed"


async def auto_pr(project: Any, session: Any, frontend_url: str = "") -> tuple[str, str]:
    """Open a GitHub PR on transition to DONE.

    Returns (status, pr_url) where status is 'success' | 'skipped' | 'failed'.
    """
    from models.db import User

    if not project.github_repo or not project.user_id:
        return "skipped", ""

    user_result = await session.exec(select(User).where(User.id == project.user_id))
    user = user_result.first()
    if not user or not user.github_token_enc:
        return "skipped", ""

    try:
        pat = decrypt_pat(user.github_token_enc)
    except Exception:
        logger.warning("auto_pr: could not decrypt PAT for project %s", project.id)
        return "skipped", ""

    branch = project.github_branch or f"sdlc/{project.id}"
    title = f"[SDLC] {project.name}"

    body_parts = [f"## {project.name}\n\n{project.description}"]
    if frontend_url:
        body_parts.append(f"\n\n[View project dashboard]({frontend_url}/app/projects/{project.id})")
    body = "".join(body_parts)

    try:
        pr_url = await create_pr(pat, project.github_repo, branch, title, body)
        return "success", pr_url
    except Exception as exc:
        logger.error("auto_pr failed for project %s: %s", project.id, exc)
        return "failed", ""
