'use client'

import { useEffect, useRef, useState, useCallback } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { getPreviewInfo } from '@/lib/api'
import type { PreviewInfo } from '@/lib/api'
import Spinner from '@/components/Spinner'

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'

export default function PreviewPage() {
  const params = useParams()
  const projectId = params.id as string
  const containerRef = useRef<HTMLDivElement>(null)

  const [info, setInfo] = useState<PreviewInfo | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [launching, setLaunching] = useState(false)

  useEffect(() => {
    getPreviewInfo(projectId)
      .then(data => { setInfo(data); setLoading(false) })
      .catch(e => { setError(e instanceof Error ? e.message : 'Failed to load'); setLoading(false) })
  }, [projectId])

  const launchStackBlitz = useCallback(async () => {
    if (!info || !containerRef.current) return
    setLaunching(true)
    try {
      const sdk = (await import('@stackblitz/sdk')).default
      sdk.embedProject(
        containerRef.current,
        {
          title: `Project Preview`,
          description: 'Generated by Orchestrator',
          template: 'node',
          files: info.files,
          settings: { compile: { trigger: 'auto' } },
        },
        {
          openFile: guessEntryFile(info.files),
          hideNavigation: false,
          height: '100%',
          terminalHeight: 30,
          devToolsHeight: 33,
        },
      )
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to launch preview')
    } finally {
      setLaunching(false)
    }
  }, [info])

  if (loading) {
    return (
      <div className="min-h-screen bg-neutral-950 flex items-center justify-center">
        <Spinner />
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-neutral-950 flex flex-col items-center justify-center gap-4">
        <p className="text-red-400 text-sm">{error}</p>
        <Link href={`/app/projects/${projectId}`} className="text-sm text-primary-400 hover:text-primary-300">← Back to project</Link>
      </div>
    )
  }

  if (!info) return null

  return (
    <div className="min-h-screen bg-neutral-950 flex flex-col">
      <header className="border-b border-neutral-800 bg-neutral-900 flex-none h-12 flex items-center px-4 gap-4">
        <Link href={`/app/projects/${projectId}`} className="text-sm text-neutral-400 hover:text-neutral-100 transition-colors flex items-center gap-1">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </Link>
        <span className="text-sm font-semibold text-neutral-200 flex-1">Project Preview</span>
        <span className="text-xs text-neutral-500 font-mono bg-neutral-800 px-2 py-1 rounded">
          {info.project_type} · {info.file_count} files
        </span>
      </header>

      {info.is_web ? (
        <div className="flex flex-col flex-1 overflow-hidden">
          {!launching && (
            <div className="flex items-center gap-3 px-4 py-2.5 bg-neutral-900 border-b border-neutral-800 flex-none">
              <span className="text-xs text-neutral-400">
                {info.file_count > 0
                  ? `${info.file_count} source files ready`
                  : 'No source files found — implementation phase may not be complete'}
              </span>
              <button
                onClick={launchStackBlitz}
                disabled={info.file_count === 0}
                className="ml-auto inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-primary-600 hover:bg-primary-500 disabled:opacity-40 disabled:cursor-not-allowed text-white transition-colors"
              >
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Launch in StackBlitz
              </button>
            </div>
          )}

          {launching && (
            <div className="flex items-center gap-3 px-4 py-2.5 bg-neutral-900 border-b border-neutral-800 flex-none">
              <Spinner />
              <span className="text-xs text-neutral-400">Launching StackBlitz…</span>
            </div>
          )}

          <div ref={containerRef} className="flex-1 bg-neutral-950">
            {!launching && info.file_count > 0 && (
              <div className="h-full flex flex-col items-center justify-center gap-4 text-center px-8">
                <div className="w-16 h-16 rounded-2xl bg-primary-950 border border-primary-900 flex items-center justify-center">
                  <svg className="w-8 h-8 text-primary-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <div>
                  <p className="text-base font-semibold text-neutral-200 mb-1">Ready to preview</p>
                  <p className="text-sm text-neutral-500 max-w-sm">
                    Click "Launch in StackBlitz" to open a live dev environment with your project running in the browser.
                  </p>
                </div>
              </div>
            )}
            {info.file_count === 0 && (
              <div className="h-full flex flex-col items-center justify-center gap-3 text-center px-8">
                <p className="text-sm font-medium text-neutral-400">No source files generated yet</p>
                <p className="text-xs text-neutral-600 max-w-sm">
                  The implementation phase needs to complete before a preview is available.
                  Agents output files using <code className="text-primary-400">&lt;file path="..."&gt;</code> tags.
                </p>
                <Link href={`/app/projects/${projectId}`} className="text-xs text-primary-400 hover:text-primary-300">
                  Go to project →
                </Link>
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto p-6 max-w-3xl mx-auto w-full space-y-6">
          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5">
            <h2 className="text-sm font-semibold text-neutral-200 mb-3">Run locally</h2>
            <p className="text-xs text-neutral-500 mb-3">
              This is a <strong className="text-neutral-300">{info.project_type}</strong> project.
              Download the zip and run the following commands in your terminal:
            </p>
            <pre className="bg-neutral-950 rounded-lg p-4 text-xs font-mono text-neutral-300 whitespace-pre-wrap">
              {info.start_command}
            </pre>
          </div>

          <div className="bg-neutral-900 border border-neutral-800 rounded-xl p-5">
            <h2 className="text-sm font-semibold text-neutral-200 mb-3">
              Generated files ({info.file_count})
            </h2>
            {info.file_count === 0 ? (
              <p className="text-xs text-neutral-500 italic">No source files generated yet — implementation phase may still be running.</p>
            ) : (
              <div className="space-y-1 font-mono text-xs">
                {Object.keys(info.files).sort().map(path => (
                  <div key={path} className="flex items-center gap-2 text-neutral-400">
                    <svg className="w-3 h-3 text-neutral-600 flex-none" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    {path}
                  </div>
                ))}
              </div>
            )}
          </div>

          <a
            href={`${API_BASE}/projects/${projectId}/download`}
            download
            className="flex items-center justify-center gap-2 w-full py-2.5 rounded-lg border border-primary-800 bg-primary-950 text-primary-300 text-sm font-medium hover:bg-primary-900 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download project (.zip)
          </a>
        </div>
      )}
    </div>
  )
}

function guessEntryFile(files: Record<string, string>): string {
  const candidates = [
    'src/app/page.tsx', 'src/pages/index.tsx', 'pages/index.tsx',
    'src/index.tsx', 'src/index.js', 'index.js', 'index.ts',
    'app/page.tsx', 'main.py', 'main.go', 'app.rb',
  ]
  for (const c of candidates) {
    if (files[c]) return c
  }
  return Object.keys(files)[0] ?? 'README.md'
}
